DATA:
    ROOT: '/path/k400'
    TRAIN_FILE: 'datasets_splits/k400_splits/train.txt'
    VAL_FILE: 'datasets_splits/k400_splits/val.txt'
    DATASET: kinetics400
    NUM_FRAMES: 16
    NUM_CLASSES: 400
    LABEL_LIST: 'labels/kinetics_400_labels.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 32 # BS 512
    ACCUMULATION_STEPS: 4
    EPOCHS: 80
    LR: 4.e-03
    WARMUP_EPOCHS: 5
    COS_DECAY_EPOCHS: 25           
    COS_DECAY_LR_MULTIPLIER: 0.05   
    STEP_DECAY_INTERVAL_EPOCHS: 5 
    STEP_DECAY_MULTIPLIER: 0.5    
TEST:
    MULTI_VIEW_INFERENCE: True
TRAINER:
  VTD_CLIP:
    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
    PROMPT_MODEL: True # If true, will only train the prompts while keeping rest of the model frozen
    N_CTX_VISION: 16
    N_CTX_TEXT: 16
    CTX_INIT: "a photo of a"
    PROMPT_DEPTH_VISION: 12
    PROMPT_DEPTH_TEXT: 12
SAVE_FREQ: 10